### ISSUE TITLE
TWRP not working properly

### ISSUE THREAD

**Issue by dupr0n** [SamarV-121/android_device_oppo_RMX1801#1]
I did the exact same method as mentioned in your [site](https://samarv-121.github.io/twrp-3.2.3-RMX1801/), but TWRP isn't reading the microSD slot. It gives 0 MB as the size of microSD and I can't select it. Also, it seems to me that TWRP starts from the beginning every time I boot to recovery as I'm getting the 'Allow modifications to system partition' in every boot. I tried wiping the data twice, which removed the internal storage data encryption, but when I booted back to TWRP, it showed it as 0 MB. I've also flashed TWRP several times, but to no avail. One thing that I noticed was that when I flashed TWRP the first time, it showed success, but when booting to recovery, it had stock recovery. I flashed TWRP again and _that_ issue was fixed.

My microSD is FAT32 format, and its contents aren't encrypted. I'm able to read the contents of it on PC and in my phone, but not in recovery. However, when in TWRP, it shows that my SD card is vfat format. I can't wipe it, repair it or change the filetype, as its showing an error.

**Comment by SamarV-121** [comment]
You need to flash magisk (it will remove dm variety)
if you don't flash then twrp will replace with stock recovery 

and for removing decryption:
Format data ( or wipe internal storage or userdada) and flash Disable-Encryption patch 

that's it 

it's tested and working fine

even SD card is totally fine

**Comment by dupr0n** [comment]
Ok. I got it. Thanks!
