### ISSUE TITLE
GPS not working on latest LOS 16 build [log attaced]

### ISSUE THREAD

**Issue by kskarthik** [SamarV-121/android_device_oppo_RMX1801#11]
Hi, Just tried the build yesterday. I flashed after a complete wipe. Everything seems to work great (except we need to press power button after boot for touch to become responsive). I have noticed that GPS is not working. I have attached the logcat output. Please check it. I will provide you more logs if required :-)

Thank you for the ROM !
[gps.log](https://github.com/SamarV-121/android_device_oppo_RMX1801/files/3863660/gps.log)

**Comment by SamarV-121** [comment]
I'll look into it

**Comment by SamarV-121** [comment]
Pm me on telegram
t.me/SamarV121

**Comment by SamarV-121** [comment]
Just asked some users and its working fine

**Comment by kskarthik** [comment]
Well, It isn't for me. Did you find anything wrong in the logs? And, are the other users using gapps. As, I am not using them. Is there anyway i can inspect more deep into this issue?

**Comment by SamarV-121** [comment]
Try to clear data of maps ;_;
