### ISSUE TITLE
USB preference Can not be changed from notification bar

### ISSUE THREAD

**Issue by r1riyad** [SamarV-121/android_device_oppo_RMX1801#12]
so whenever we connect a usb cable with phone there is  a notification which shows charging device . By selecting that notification we should be change the device usb mode to File Transfer or USB tethering mode that is not possible in the ROM.I attached a Screenshot for better Understanding.
![Screenshot_20191208-145204_Settings](https://user-images.githubusercontent.com/33262712/70387072-d4a6a280-19ca-11ea-9ed8-a8c15fc53767.png)
All options are faded away!

N.B. - I changed the mode from developer setting where it can be changed easily..

**Comment by SamarV-121** [comment]
Fixed in lineage-17.1-20200309-UNOFFICIAL-RMX1801.zip
 https://samarv-121.github.io/lineageos-17.1-RMX1801/
