### ISSUE TITLE
Battery Indicator not changing

### ISSUE THREAD

**Issue by jerinjacob007** [SamarV-121/android_device_oppo_RMX1801#13]
When battery indicator changed to other design and percentage enabled it's not changing/showing in the status bar even after restart.

![Screenshot_20200108-210801_LineageOS_Settings](https://user-images.githubusercontent.com/23569103/71992351-4177bb80-325b-11ea-999c-2576cbd2b899.png)

**Comment by SamarV-121** [comment]
los havent implemented that feature
wait for it
