### ISSUE TITLE
camera: can't take a picture when HDR mode enabled.

### ISSUE THREAD

**Issue by MBAHPOMADE** [SamarV-121/android_device_oppo_RMX1801#14]
I cant take a picture when HDR mode enabled, but it will back to normal again when i close the app and turn off the HDR mode. here i provide a [logcat.](https://pastebin.com/ckHqv55H)  for you

**Comment by SamarV-121** [comment]
In which app?

**Comment by MBAHPOMADE** [comment]
> In which app?

Default camera apl

**Comment by SamarV-121** [comment]
@MBAHPOMADE Lel

**Comment by MBAHPOMADE** [comment]
> @MBAHPOMADE Lel

😂😂😂😂😂

**Comment by SamarV-121** [comment]
Which rom btw

**Comment by SamarV-121** [comment]
And snap camera?

**Comment by MBAHPOMADE** [comment]
> Which rom btw

Pixel Experience RMX1801 Build 26012020

**Comment by MBAHPOMADE** [comment]
> And snap camera?

Idk. i've just test the rom w/o any kernel/default app modifications.😂

**Comment by SamarV-121** [comment]
@MBAHPOMADE Enable camera2api and use gcam :3
