### ISSUE TITLE
Cast doesnt work

### ISSUE THREAD

**Issue by AquamanRanda** [SamarV-121/android_device_oppo_RMX1801#5]
When I try to use cast in my  lineage os the phone goes off for quite a sec and then comes to the lock screen 

I have attached the logcat file  

[cast.txt](https://github.com/SamarV-121/android_device_oppo_RMX1801/files/3714401/cast.txt)

**Comment by SamarV-121** [comment]
Can you try on pixel experience once

**Comment by AquamanRanda** [comment]
I even tried it with pixel experience and this is what it showed 
![Screenshot_20191011-115138](https://user-images.githubusercontent.com/41387473/66628820-959fdf00-ec1d-11e9-9c9b-3b71834b304c.png)

**Comment by SamarV-121** [comment]
;_;

**Comment by SamarV-121** [comment]
Give log of this
