### ISSUE TITLE
sdcard does not work

### ISSUE THREAD

**Issue by snapfast** [SamarV-121/android_device_oppo_RMX1801#7]
sdcard not visible in any files app.

Do you need anything else? For logs, what's the process?

#
![Screenshot_20191023-021512](https://user-images.githubusercontent.com/5176514/67331187-107cca00-f53b-11e9-82bd-117b39acd6e1.png)

**Comment by snapfast** [comment]
Pixel Experience 9.0 PIE

**Comment by snapfast** [comment]
Hello Samar,

How can I fix the sdcard formatting issue on the pixel Experience? If the issue is not in the scope for a Fix. Kindly suggest me another ROM. Thank you.

Rahul

**Comment by SamarV-121** [comment]
There is no such issue 
Clean flash it

**Comment by snapfast** [comment]
Flashing C.24 Vendor + Firmware did work !
